#!/bin/bash

- name: configuring catalogue service
  hosts: catalogue
  become: yes
  tasks:
  - name: disable the default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable the nodejs 20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: installing the nodejs 20 version
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: creating system user
    ansible.builtin.user:
      name: roboshop system user
      state: present
      system: yes # This parameter makes it a system user
      shell: /sbin/nologin # Typically, system users do not have login shells

  - name: download code to tmp directory
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: changing the app directory
    ansible.builtin.command: cd /app

  - name: unzipping the file into app directory
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    community.general.npm:
      path: /app
      state: present
    
  

