#!/bin/bash

- name: configuring rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copying rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: enable and start the service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes
  
  